name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: ghlee7411/cake
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: cd docs && yarn && yarn build
        BUILD_DIR: src/.vuepress/dist/